### ISSUE TITLE
Times for decay chains / killed nuclei

### ISSUE THREAD

**Issue by tdixon97** [legend-exp/remage#135]
* If we simulate decay chains with steps with very long livetimes we may get numerical issues when time-windowing the outputs. Since we look at the time-difference between G4Steps and the first step in the evt, if these are very large the difference will be 0.
* I simulated Ra-224 with the following commands.

```/RMG/Generator/Select GPS  
/gps/particle ion
/gps/energy 0 eV
/gps/ion 88 224
/process/had/rdm/nucleusLimits 208 224 81 88
```
* This leads to times that are large (as expected due to few days Ra-224 half-life), eg times for one event are
 ```[3.11e+14, 3.11e+14, 3.11e+14, 3.11e+14, ..., 3.11e+14, 3.11e+14, 3.11e+14] ns``` 
 but these still allow to determine delta t with < 1 ns precision.

* But if we would like to simulate decays with longer half-lives (Ra-226, U-238 etc.) we get into issues, as well as if a part of the decay chain has a long half-life.
* However, when I tried simulating Ra-226 I got no events in the output file, so the nuclei is being killed before the decay (without a warning message etc.). Seems related to [stepping-action](https://github.com/legend-exp/remage/blob/main/src/RMGSteppingAction.cc#L30), maybe we need some warnings if the user tries to simulate decays with T12 ~ time to kill nuclei?
* @ManuelHu  do we need a solution to allow simulation of arbitary decays including those with long half-lives?

**Comment by ManuelHu** [comment]
Geant4 11.2 changed the default value of the max lifetime to 1 year (yeah, I also think this is bad to change it in a minor release)

reset to old default (maybe we should add this to remage to make it behave consistently):
```
/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year
```

> Seems related to [stepping-action](https://github.com/legend-exp/remage/blob/main/src/RMGSteppingAction.cc#L30),

this feature to kill long-lived daughter nuclei should be disabled by default; `fDaughterKillLifetime` should be -1, if you do not set it in a macro.

**Comment by tdixon97** [comment]
Ok that makes sense.
So we shouldn't have any issues with numerical precision for times < 1 yr (a double can hold the number of ns in a year without any loss of precision below 1ns).
Although if we increase this using the command you we will start to have the issues I was worried about regarding numerical issues with time-differences for windowing into events.
Should we try to think of a solution? Maybe not letting users simulate these decays and exiting with an error is the best short-term solution

**Comment by ManuelHu** [comment]
Shouldn't those problems also exist in MaGe? If we have a solution there, we could try to implement something similar

**Comment by tdixon97** [comment]
Yes probably, although maybe in MaGe I notice all the macros simulate short half-life decays (Eg Rn222 not Ra226), so maybe there is no solution. We could check (although finding out whats happening in MaGe is not easy).

**Comment by gipert** [comment]
#136 and #160 look good to merge.

To do: add way to disable the warning.
