### ISSUE TITLE
Wrong nested list indentation in `rmg-commands.rst`

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#149]
This is the right way to format nested lists:

```
- first bullet

  - nested 1
  - nested 2

- second bullet
```

i.e. the empty line after the outermost bulled and the nested bullet being aligned with the start of the text in the outermost bullet are important. I couldn't figure out how to fix this in `docs/g4manual2rst.py`...

**Comment by ManuelHu** [comment]
I actually don't want to fix this in `g4manual2rst.py` 😅 - the nesting code is already unbelievable complex.(*)

We should maybe call it `g4manual2md.py` ; it should mostly already output valid markdown (especially after your PR #145 ). And markdown is much more forgiving for such indentation subleties...

(*) partly rooted in the geant4 manual "format" not having a fixed indentation space count. It's _very_ messy.
