### ISSUE TITLE
Pre-compute rough distance to HPGe surface

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#154]
We should investigate whether there is a simple way to roughly determine the distance of energy depositions from the HPGe surface. This would be very useful in post-processing to fold the activeness map only with points that are reasonably close to the surface, and therefore speed up computation.

One idea could be to define an additional, nested, sensitive volume, but I think this has several downsides.

**Comment by EricMEsch** [comment]
My first idea regarding a really simple solution to estimate an upper boundary on the distance: Take the vector between where the particle entered the volume and the energy deposition. You could then calculate the distance to the entrance point. The real distance will always be equal or less.

That would be a simple way to get an upper boundary, but i guess we rather need a lower boundary?

**Comment by EricMEsch** [comment]
A better option i think would be to use the `ComputeStep()` function of the `G4Navigator` and sample a few directions. Although i am not sure about how computational intensive that would be, but certainly better than nested volumes.

**Comment by ManuelHu** [comment]
There are also some geometry functions from geant directly:

```
    virtual G4double DistanceToIn(const G4ThreeVector& p) const = 0;
      // Calculate the distance to the nearest surface of a shape from an
      // outside point. The distance can be an underestimate.

    virtual G4double DistanceToOut(const G4ThreeVector& p,
				   const G4ThreeVector& v,
				   const G4bool calcNorm=false,
				   G4bool* validNorm = nullptr,
				   G4ThreeVector* n = nullptr) const = 0;
      // Return the distance along the normalised vector v to the shape,
      // from a point at an offset p inside or on the surface of the shape.
      // Intersections with surfaces, when the point is < Tolerance/2 from a
      // surface must be ignored.
      // If calcNorm==true:
      //    validNorm set true if the solid lies entirely behind or on the
      //              exiting surface.
      //    n set to exiting outwards normal vector (undefined Magnitude).
      //    validNorm set to false if the solid does not lie entirely behind
      //              or on the exiting surface
      // If calcNorm==false:
      //    validNorm and n are unused.
      //
      // Must be called as solid.DistanceToOut(p,v) or by specifying all
      // the parameters.

    virtual G4double DistanceToOut(const G4ThreeVector& p) const = 0;
      // Calculate the distance to the nearest surface of a shape from an
      // inside point. The distance can be an underestimate.
```

(and some more variants)

I am unsure, `DistanceToOut` seems right for inside points?

**Comment by gipert** [comment]
They sound useful but I don't know what they do, we should have a look at the source code...

**Comment by gipert** [comment]
To do:
- check what these Geant4 functions actually do and if using them would significantly slow down the simulation
- do some literature research, I can't believe we are the first facing this problem

**Comment by EricMEsch** [comment]
If no one volunteered so far i can check the source code of these functions and test the impact of their use on the simulation. (And also test if they work as expected for some simple geometries)
I can also try some literature research, if any one encountered problems with these solutions. But, in case the solution works reliable i guess no one faced that problem before, because there is not really a problem

**Comment by gipert** [comment]
This would be great @EricMEsch! I'll assign you to the issue
