### ISSUE TITLE
Add support for GRDM generator

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#158]
https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/Fundamentals/biasing.html?highlight=grdm#radioactive-decay-biasing

**Comment by gipert** [comment]
In MaGe, this is used to simulate decay chain segments by setting start and stop nucleus.

```
/MG/generator/select RDMiso
/gun/energy 0 eV
/grdm/ion 228 89 0
/grdm/nucleusLimits 228 228 88 89
```
 This is of course analogous to GPS ion + livetime limit but is sometimes more "readable" in a macro.

**Comment by ManuelHu** [comment]
it's 1 year; so much to short for most of our isotopes(*). Maybe we should set it in remage... (see also #135 where Toby noticed this)

(*) `thresholdForVeryLongDecayTime` applies both to primaries and secondaries (unlike our limit), so you might not even get any events simulated.
