### ISSUE TITLE
New output table to store track vertex information

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#178]
This would be extremely useful for validation/debugging.

- Store the track vertices (this is currently not possible), including particle type, position, kinematics and possibly creation process
- For the latter: come up with our (automatic) numbering
- Implement basic filtering with macro commands, i.e. creation process,  particle type, energy

Related: #162

**Comment by EricMEsch** [comment]
> (this is currently not possible)

You mean not possible with the current ReMaGe options? As i have implemented that for my own simulations more often than i can count :grinning:

So i can certainly do this, i should be finished testing the distance to surface one soon. 

Open questions:
* With "track vertices" you mean the creation vertex of each track? That should be done in tracking. If you mean each single step, then it should be done in stepping (but would also lead to waaayyy more clutter in the output)
* Should this still be an `OutputScheme`, or part of the `TrackingAction`/`SteppingAction`? For only the Track vertices making an optional `OutputScheme` would be no issue with the hook in the `PreUserTrackingAction()` already existing, but if this should output every step information, then i would also have to add a hook into the `UserSteppingAction()` (which could slow down the simulation, but if you hide it behind a macro its fine i guess)
* For the automatic numbering scheme i guess we have to discuss (or just tell me the scheme if you have already something)

**Comment by ManuelHu** [comment]
I have already working code for this :-)

* only the track vertices are of interest at the moment
* yes, it will be an output scheme. There is no reason to store the info in memory if nobody wants actually to write it to output.
* the process numbering scheme is actually quite rudimentary. As there is no global process index in geant4, we can only assign numbers ourselves. My code will also create a lookup table in the output file (*)

(*) storing strings directly is extremely ineffetive, so we just use the lookup table to store the process names once
