### ISSUE TITLE
Possible bug in sampling from multiple sources

### ISSUE THREAD

**Issue by tdixon97** [legend-exp/remage#209]
It seems that when we try to sample from multiple sources we do not get the correct fraction of vertices in each physical volume (according to their volume).

> **Summary**: After alot of checks I find this is due (atleast partially) to the way the `IsInside` check acts on the full list of volumes and bounding boxs can overlap.

I simulated events (100 keV beta's) in the Germanium detectors for L-200 (i.e. using the following macro).
```
/control/execute cfg/detectors.mac
/RMG/Output/NtuplePerDetector false
/run/initialize

/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/Physical/AddVolume B.*
/RMG/Generator/Confinement/Physical/AddVolume C.*
/RMG/Generator/Confinement/Physical/AddVolume P.*
/RMG/Generator/Confinement/Physical/AddVolume V.*

/RMG/Generator/Select GPS
/gps/particle e-
/gps/energy 100 keV

/run/beamOn 1000000
```
I then plotted the fraction of vertices in each detector (making use of `legendhpges.is_inside` for the check). I also plotted the fraction of hits (taking the first uid in the hit as the channel). I compare this to the expectation according to the detector volume.

```python
from lgdo import lh5
from matplotlib import pyplot as plt
import awkward as ak
import numpy as np
from tqdm import tqdm
import legendhpges as hpges
import pyg4ometry as pg4
from numpy import pi
from pygeomtools.detectors import get_sensvol_metadata
import copy

plt.rcParams["lines.linewidth"] = 1
plt.rcParams["font.size"] = 12


# get the detector info
reg = pg4.gdml.Reader("cfg/l200.gdml").getRegistry()
reg_tmp = pg4.geant4.Registry()
detectors = list(reg.physicalVolumeDict.keys())

detectors = [det for det in detectors if det[0] in ["V","P","B","C"]]

det_map = {det: {"uint":get_sensvol_metadata(reg,det)["daq"]["rawid"],
                 "pos":reg.physicalVolumeDict[det].position.eval(),
                 "hpge":hpges.make_hpge(get_sensvol_metadata(reg,det),registry=reg_tmp)} for idx,det in enumerate(detectors)}

# get vertices and add which detector it is in
# append with the uint and the local positions
vertices = lh5.read_as("stp/vertices","output/l200_beta.lh5","ak")

uint = np.array(np.full_like(vertices.time,-1),dtype=int)
xlocal = np.array(1000*vertices.xloc)
ylocal = np.array(1000*vertices.yloc)
zlocal = np.array(1000*vertices.zloc)

positions = np.array(np.transpose(np.vstack([vertices.xloc*1000,vertices.yloc*1000,vertices.zloc*1000])))
for det in tqdm(det_map.keys()):
    if (det=="V02160A"):
        continue
        
    local_positions = copy.copy(positions)
    local_positions-=det_map[det]["pos"]

    is_inside = det_map[det]["hpge"].is_inside(local_positions)

    uint[is_inside]=det_map[det]["uint"]
    xlocal[is_inside]-=det_map[det]["pos"][0]
    ylocal[is_inside]-=det_map[det]["pos"][1]
    zlocal[is_inside]-=det_map[det]["pos"][2]

vertices["uid"]=uint
vertices["xlocal"]=xlocal
vertices["ylocal"]=ylocal
vertices["zlocal"]=zlocal

# get the uid per hit

steps = lh5.read_as("stp/germanium","output/l200_beta.lh5","ak")
steps = ak.unflatten(steps, ak.run_lengths(steps.evtid))
uid= ak.fill_none(ak.firsts(steps.det_uid,axis=-1),-1)
evtid = ak.fill_none(ak.firsts(steps.evtid,axis=-1),-1)
hits = ak.Array({"evtid":evtid,"uid":uid})

# plot the fraction of vertices in each channel
def make_plot(vert,hit):
    
    fraction_vert= []
    fraction_vert_err = []
    fraction_hit = []
    expected_fraction = []
    names = []

    n_tot = len(vert)
    vol_tot = 0 

    for det in det_map.keys():
        vol_tot +=float(det_map[det]["hpge"].volume.magnitude)

        if (det=="V02160A"):
            continue
        n_sel_vert  = len(vert[vert.uid==det_map[det]["uint"]])
        n_sel_hit   = len(hit[hit.uid==det_map[det]["uint"]])
        
        names.append(det)
        fraction_vert.append(100*n_sel_vert/n_tot)
        fraction_vert_err.append(100*np.sqrt(n_sel_vert)/n_tot)
        fraction_hit.append(100*n_sel_hit/n_tot)
        expected_fraction.append(float(det_map[det]["hpge"].volume.magnitude))

    expected_fraction = 100*np.array(expected_fraction)/vol_tot
    fraction_vert= np.array(fraction_vert)
    fig, ax = plt.subplots(figsize=(16,4))

    ax.errorbar(np.arange(len(names)),fraction_vert,yerr=fraction_vert_err,fmt=".",label="Vertices")
    ax.errorbar(np.arange(len(names))-0.1,fraction_hit,fmt="x",label="Hits")

    ax.errorbar(np.arange(len(names)),expected_fraction,fmt=".",label="Expected")
    ax.set_xlabel("Channel Index")
    ax.set_ylabel("Fraction of vertices [%]")
    ax.set_xticks(np.arange(len(names)),names,rotation=90,fontsize=10)
    ax.legend()
    ax.grid()
    plt.tight_layout()

make_plot(vertices,hits)
```

The result is quite large deviations from the expectation. However, the fraction of vertices matches quite closely the fraction of hits (suggesting I didn't make a mistake in my script). I checked the script and I do not see any obvious issue.
![image](https://github.com/user-attachments/assets/e914977f-5a5b-4915-bd20-0e103df6f17e)
This appears both with and without multithreading...

To show a bit more closely I zoomed into some channels.
![image](https://github.com/user-attachments/assets/1ca34b3e-6f67-4aea-913d-93ec5fcf55bc)
We see for some (usually large detectors) very large deviations, while others appear fairly compatible with the expectation.

We should check this carefully and understand the bug.. ideas:
- [x] check if the bug appears in the single-threaded mode (it does)
- [x] look at a simplified geometry (just few volumes),
- [x] check volume in `pyg4ometry` vs geant4
- [x] check the position of vertices especially for channels with large deviations
- [x] add some more debug information

**Comment by tdixon97** [comment]
## 1) Simplified geometry

The first thing I tried is to see if we can reproduce this on a smaller scale.
I used the geometry of the [[remage-tutorial]](https://remage.readthedocs.io/en/stable/tutorial.html)
 -  Sample 1 MeV e-’s in the two HPGes
- Check the number of vertices in each detector (both vertex and hit table)
 - Compatible with the expectation from detector volume
 
![image](https://github.com/user-attachments/assets/5a408e80-0fd6-4d3b-879e-1a3ec7b1bfea)

This seems ok, but maybe for these particular detectors a larger statistic is needed to see the deviation.

**Comment by tdixon97** [comment]
# 2) Check volume

Compared the volume print out for the detectors in `geant4` (I ran the simulation in debug mode and I captured the output) compared to that computed by `legend-hpges`.
Find a perfect agreement:
![image](https://github.com/user-attachments/assets/4bf0bf87-c506-4ee9-9991-8a410bf04c9d)

**Comment by tdixon97** [comment]
## 3) Sampled vertex positions

Focused on the channels with the largest (>40% relative difference) deviations:
![image](https://github.com/user-attachments/assets/a5b9e42e-e273-44f7-a1d7-6ec9a21cb240)

Having a quick look the vertex positions look reasonable compared to the expected origin:

![image](https://github.com/user-attachments/assets/652fbb8f-d593-4c4d-bd91-1f558ecf550f)
![image](https://github.com/user-attachments/assets/d627c517-1416-45b7-9e9c-5c26a21fc5d4)

I try a more detailed check by comparing the local positions to the detector profile.

It looks fine 
in all cases (some examples below):
![image](https://github.com/user-attachments/assets/146dc35c-1b2b-499f-962b-c3cabe62ec64)
![image](https://github.com/user-attachments/assets/7c1a306c-2210-4949-a5b6-60bcdf1b33d9)
![image](https://github.com/user-attachments/assets/403ea9a5-887c-495b-ab53-5452e24624de)

**Comment by tdixon97** [comment]
### 4) More debug info

It seems from the past check the issue is in the selection of a volume (not the sampling itself, or the volumes of solids).
So this function is the suspect one:
```c++

const RMGVertexConfinement::SampleableObject& RMGVertexConfinement::SampleableObjectCollection::
    VolumeWeightedRand() const {

  if (data.empty()) RMGLog::OutDev(RMGLog::fatal, "Cannot sample from an empty collection");

  auto choice = this->total_volume * G4UniformRand();
  double w = 0;
  for (const auto& o : this->data) {
    if (choice > w and choice <= w + o.volume) return o;
    w += o.volume;
    if (w >= this->total_volume) {
      RMGLog::Out(RMGLog::error, "Sampling from collection of sampleables failed unexpectedly ",
          "(out-of-range error). Returning last object");
      return this->data.back();
    }
  }
  return this->data.back();
}
```

I tried modifying to dump the random numbers used to select a volume, the chosen volumes and the boundaries (`w` values).
When doing this we find a good agreement in the returned volumes.

![image](https://github.com/user-attachments/assets/2cc7012a-4a58-472a-82f1-5f78fd3ba1b5)
![image](https://github.com/user-attachments/assets/6409945b-0e06-45d0-83b0-8829048cabad)

So even though this function returns the correct fraction of each volume something goes wrong somewhere else. Hmm..

**Comment by tdixon97** [comment]
I checked the bounding boxes for the sampling (modified the code to save the information), For example for one channel:
![image](https://github.com/user-attachments/assets/ba39aaf0-c5ce-4ab0-b188-3f24519139f9)
Generally the bounding boxes for the volumes can overlap in z. For example looking at one string:
![Uploading image.png…]()
So this means that some primaries generated in solid A, can end up instead in solid B, they then pass the `IsInside` check which acts on the full `fPhysicalVolumes`. This alters the fraction of primaries in each solid.

**Comment by tdixon97** [comment]
Modified this by making a new `RMGVertexConfinement::SampleableObjectCollection` called `selected_sources` containing just `choice` (for this code). A perhaps nicer approach is to just make a method `IsInside` of `SampleableObject`.
Anyway, running again the original simulation I find it is now fixed.
![image](https://github.com/user-attachments/assets/9199997e-f8da-4972-9a69-b3a9dd588bc9)

**Comment by EricMEsch** [comment]
I am just back from vacation, this is a great and illustrative investigation you did :grinning:
