### ISSUE TITLE
Technical dev items

### ISSUE THREAD

**Issue by gipert** [legend-exp/remage#21]
- [x] Include test suite in CI, label tests of "extra" features, run multithreaded
- [x] Revise UI command states
- [x] Revise where UI commands are defined
- [x] Evaluate performance (vertex generator)
- [x] remove `RMGLog` support for file logging
- [x] implement barebones `remage` executable (use CLI11)

**Comment by ManuelHu** [comment]
Outstanding items for command states:
* [ ] Check if/how the random seed commands work in MT mode
* [ ] Check vertex confinement command logic
