### ISSUE TITLE
Install Remage headers to project scoped directory?

### ISSUE THREAD

**Issue by drbenmorgan** [legend-exp/remage#34]
One follow up to #33 is to ask if we want to install Remage's headers to a subdirectory on `include/`, e.g. `Remage/RMG...h`? Whilst the naming scheme makes clashes unlikely, it does neaten things little. Also, the third-party `fmt` and `magic_enum` header-only projects are installed directly in `include`. Should there be existing installs of those in the `CMAKE_INSTALL_PREFIX`, Remage will stomp on them at install/uninstall. Putting these in e.g. `Remage/fmt/...` avoids conflict and should also avoid API/ABI clashes in simple cases (e.g. Remage used its own `fmt`, but consumer has another `fmt` version that's at a higher priority include location).

**Comment by gipert** [comment]
I agree that what we have right now is non-optimal. I thought about installing headers in `include/remage` at the beginning but then decided to add the `RMG` prefix everywhere. I did not have subfolders containing third-party headers at that time...

I wonder whether we should do the painful `include/RMG*.hh` -> `include/remage/*.hh` renaming now while the software is still in a heavy development stage.
