### ISSUE TITLE
Add a way to load/register detectors without recompiling the application

### ISSUE THREAD

**Issue by ManuelHu** [legend-exp/remage#62]
Currently, there is no way to call `RMGHardware::RegisterDetector` without writing your own C++ application based on remage. This would be very useful for external applications producing GDML as output, so that they could also produce a sidecar "detector list" or similar.

In the past I tried to add some macro commands for this, but I never succeeded to get them working early enough (i.e. after loading the GDML file but before "finalizing" the detector construction). Another option would be to have some sort of data file (maybe some sort of JSON?), that the `remage` utility can load before initializing macros.

* detector type
* physical volume
* detector ID in the output file
* copy nr - shouldn't this be zero in all cases when dealing with GDML?
* maybe some human readable name/grouping?

**Comment by gipert** [comment]
Can you elaborate more on why this is not achievable with a macro command? Can't the Detector meta data be registered even before GDML parsing and then actually fed to `RMGHardware::RegisterDetector` at the right moment?

**Comment by ManuelHu** [comment]
Just my bad memory apparently. #63 works.
