### ISSUE TITLE
Dangling pointers in RMGVectorConfinement leading to segfault

### ISSUE THREAD

**Issue by ManuelHu** [legend-exp/remage#7]
Some forms of confinement (both for a complex physical volume `/RMG/Generator/Confinement/Physical/AddVolume` as well as a geometrical confinement `/RMG/Generator/Confinement/Physical/AddSolid`) create temporary `G4VSolid`s for bounding box calculations.

A pointer to the solid is stored in `RMGVertexConfinement::SampleableObject::sampling_solid`. The `SampleableObject`s destructor deletes the refereced solid, if it has been a temporary one:
https://github.com/gipert/remage/blob/6ba1bc6bae0fe0b3be8e98edb06c984c55f97042/src/RMGVertexConfinement.cc#L39-L43

The `SampleableObject` gets deleted before all calculations have been done, thus destroying the Solid instance by invalidiating the pointer to it. The next try to access the sampling_solid leads to a segfault.

A temporary "fix" to make confinement work is to uncomment the `delete` statement. While the solid is still referenced with a dangling pointer to the `SamplingObject` (as this has been somehow deleted), this *seems* to be quite stable.

---

Additionally, the access to `physical_volume` in the above destructor might lead to a nullptr dereference, as `physical_volume` is not set for Geometrical confinement:
https://github.com/gipert/remage/blob/6ba1bc6bae0fe0b3be8e98edb06c984c55f97042/src/RMGVertexConfinement.cc#L267-L270

**Comment by gipert** [comment]
All this should be now fixed in `main`.
