### ISSUE TITLE
Output scheme for mpp

### ISSUE THREAD

**Issue by MoritzNeuberger** [legend-exp/remage#84]
I suppose the long-term goal would be to be able to pipe into [mpp](https://github.com/legend-exp/mage-post-proc/tree/main).
Neither of the output schemes is currently usable for it.
Looking at the structure of [MPPG4SimpleStepsReader.cc](https://github.com/legend-exp/mage-post-proc/blob/main/StepsReaders/src/MPPG4SimpleStepsReader.cc), it seems like mpp assumes the input is in the MCRun output based on MGDO.
Would it make sense to implement MCRun in remage or define our own and create a new step reader class in mpp?

**Comment by gipert** [comment]
I would rather invest some time in re-implementing the post-processing tools in python. I have already discussed this with @ManuelHu: remage could write G4 HDF5 files which we could convert to LH5 on the fly. The post-processing package would start from this.
