### ISSUE TITLE
Output scheme option to write only when a certain isotope  is produced

### ISSUE THREAD

**Issue by MoritzNeuberger** [legend-exp/remage#86]
Especially for cosmogenic production studies, a large amount of exposure has to be simulated. 
To avoid writing too much output, I propose a macro command that specifies that events are only stored when a specified isotope is produced.
It should be a relatively simple condition in the EndOfEventAction.

**Comment by EricMEsch** [comment]
Additionally, having a macro that changes the stackingaction in a way that optical photons are only produced when that certain isotope is produced, otherwise they are discarded, would greatly increase computational speed
